theme: jekyll-theme-minimal
repository: mithunshanbhag/mithunshanbhag.github.io
logo: images/logo_400_400.jpg

# 
author: 
  name: Mithun Shanbhag
  github: https://github.com/mithunshanbhag
  linkedin: https://www.linkedin.com/in/mithunshanbhag/
  twitter: https://twitter.com/MithunShanbhag
  

# SEO related
title: Mithun Shanbhag
description: Is anyone actually reading this?
url: https://www.mithunshanbhag.com

# 
plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: posts
    values:
      comments: false
