theme: jekyll-theme-minimal
repository: mithunshanbhag/mithunshanbhag.github.io
author: 
  name: Mithun Shanbhag
  linkedin: https://www.linkedin.com/in/mithunshanbhag/
  twitter: https://twitter.com/MithunShanbhag
logo: images/logo_200_200.jpg
plugins:
  - jekyll-feed
  - jekyll-mentions