theme: jekyll-theme-minimal
repository: mithunshanbhag/mithunshanbhag.github.io
logo: images/logo_400_400.jpg

# 
author: 
  name: Mithun Shanbhag
  github: https://github.com/mithunshanbhag
  linkedin: https://www.linkedin.com/in/mithunshanbhag/
  twitter: https://twitter.com/MithunShanbhag
  instagram: https://www.instagram.com/mithunshanbhag/
  

# SEO related
title: Mithun Shanbhag
description: Is anyone actually reading this?
url: https://www.mithunshanbhag.com
twitter:
  username: MithunShanbhag
  card: summary
social:
  name: Mithun Shanbhag
  links:
    - https://twitter.com/MithunShanbhag
    - https://www.linkedin.com/in/mithunshanbhag/
    - https://github.com/mithunshanbhag

# 
plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: posts
    values:
      comments: false
      image: /images/logo_400_400.jpg
